version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification_db
    ports:
      - "5432:5432"

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"

  notification-api:
    build: .
    depends_on:
      - kafka
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/notification_db
      KAFKA_BROKER: kafka:9092
    command: bun run src/index.ts

  notification-worker:
    build: .
    depends_on:
      - kafka
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/notification_db
      KAFKA_BROKER: kafka:9092
    command: bun run src/workers/notification.worker.ts